//go:build ignore

//go:generate go run generate.go

package main

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

const outputFile = "manifest_generated.go"

type rawManifest struct {
	Versions map[string]rawVersion `yaml:"versions"`
}

type rawVersion struct {
	Tag       string        `yaml:"tag"`
	BaseName  string        `yaml:"base_name"`
	BaseURL   string        `yaml:"base_url"`
	Artifacts []rawArtifact `yaml:"artifacts"`
}

type rawArtifact struct {
	Arch    string `yaml:"arch"`
	Runtime string `yaml:"runtime"`
	URL     string `yaml:"url"`
	Digest  string `yaml:"digest"`
}

func main() {
	data, err := os.ReadFile("manifest.yaml")
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to read manifest.yaml: %v\n", err)
		os.Exit(1)
	}

	var manifest rawManifest
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		fmt.Fprintf(os.Stderr, "failed to parse manifest.yaml: %v\n", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	b.WriteString("package images\n\n")
	b.WriteString("// Artifact describes a downloadable VM base image.\n")
	b.WriteString("type Artifact struct {\n")
	b.WriteString("\tURL    string\n")
	b.WriteString("\tDigest string\n")
	b.WriteString("}\n\n")
	b.WriteString("// Version holds all artifacts for a given OS version.\n")
	b.WriteString("type Version struct {\n")
	b.WriteString("\tTag       string\n")
	b.WriteString("\tArtifacts map[string]map[string]Artifact // arch -> runtime -> artifact\n")
	b.WriteString("}\n\n")
	b.WriteString("// Manifest is the embedded registry of VM base images.\n")
	b.WriteString("var Manifest = map[string]Version{\n")

	for versionKey, version := range manifest.Versions {
		b.WriteString(fmt.Sprintf("\t%q: {\n", versionKey))
		b.WriteString(fmt.Sprintf("\t\tTag: %q,\n", version.Tag))
		b.WriteString("\t\tArtifacts: map[string]map[string]Artifact{\n")

		// group by arch, then runtime
		archMap := make(map[string]map[string]rawArtifact)
		for _, art := range version.Artifacts {
			if archMap[art.Arch] == nil {
				archMap[art.Arch] = make(map[string]rawArtifact)
			}
			archMap[art.Arch][art.Runtime] = art
		}

		for arch, runtimes := range archMap {
			b.WriteString(fmt.Sprintf("\t\t\t%q: {\n", arch))
			for runtime, art := range runtimes {
				b.WriteString(fmt.Sprintf("\t\t\t\t%q: {URL: %q, Digest: %q},\n", runtime, art.URL, art.Digest))
			}
			b.WriteString("\t\t\t},\n")
		}
		b.WriteString("\t\t},\n")
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n")

	if err := os.WriteFile(outputFile, []byte(b.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "failed to write %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	gofmtCmd := exec.Command("gofmt", "-w", outputFile)
	gofmtCmd.Stdout = os.Stdout
	gofmtCmd.Stderr = os.Stderr
	if err := gofmtCmd.Run(); err != nil {
		fmt.Fprintf(os.Stderr, "gofmt failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s successfully.\n", outputFile)
}
