// Code generated by go generate; DO NOT EDIT.

package images

// Artifact describes a downloadable VM base image.
type Artifact struct {
	URL    string
	Digest string
}

// Version holds all artifacts for a given OS version.
type Version struct {
	Tag       string
	Artifacts map[string]map[string]Artifact // arch -> runtime -> artifact
}

// Manifest is the embedded registry of VM base images.
var Manifest = map[string]Version{
	"24.04": {
		Tag: "master",
		Artifacts: map[string]map[string]Artifact{
			"arm64": {
				"none":       {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-arm64-none.qcow2", Digest: "sha512:889177b15989828c7a6da39c25603ba1ba8e1c6202f7f94e91587f049b6cb5344fea20ddec91502a42cedfcc8b57937b3bcd6fd7cbc7d267d9882b6ce67235ab"},
				"docker":     {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-arm64-docker.qcow2", Digest: "sha512:8b823c56696f1483d01b703883c962be34d382782999ee5ffcd4088702fab9ee62198f74ddfaa43af8269b580695e53bfc4a4c8e64e713436187cf8f483b8324"},
				"containerd": {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-arm64-containerd.qcow2", Digest: "sha512:22e05124b507cb87b542ea48b1e4d4457dd7503a069ecd98c7d825b32ec5ba7685bd1930fc4177e73571c9f84c77e5b0c7d9722291a2d69a2e49894180cfccbe"},
				"incus":      {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-arm64-incus.qcow2", Digest: "sha512:c0f73c52208a51ca72d626962cde31a6e572815e84cd5e58a56faf700f28821cb8848e75d9d9c974656561403c25b4ea1ba5b325d40885a0e7fd5cc9386dc7a7"},
			},
			"amd64": {
				"containerd": {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-amd64-containerd.qcow2", Digest: "sha512:0a079fedc0d5e621ce69caf176a21aac316fb227c25dd29600876965af7dc3c35ac8d00184fafe1afed8b3d4ee83b146297be5d881c19709abeaeada46eac401"},
				"incus":      {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-amd64-incus.qcow2", Digest: "sha512:3190b56223a6b6bee4b69962bbc3d9efb45bb0c14e0e4f5baf76c6b4d4c2072515021462ef2eb9c607395d21b995c63b6a8c34a3363fb0bcec44fb1870c45d0d"},
				"none":       {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-amd64-none.qcow2", Digest: "sha512:b767410296c1d2c8b575a65f26480a7a689d50917a48c7559e4cf9f4971f17660f7c12023edb12774484f58c6b4774f1d68d85270de7196f0210edc38265226e"},
				"docker":     {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-24.04-minimal-cloudimg-amd64-docker.qcow2", Digest: "sha512:c32cd1a691ee8e6ec140e66c11653a6081e3f1987bf13727b86682bd02e880cd3bc8ab46dce4102004d788c66a66cf45306e0d7ff3d7292d9f5533a5136fc3f9"},
			},
		},
	},
	"26.04": {
		Tag: "master",
		Artifacts: map[string]map[string]Artifact{
			"arm64": {
				"none":       {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-26.04-minimal-cloudimg-arm64-none.qcow2", Digest: "sha512:f220baa28df3c7fafbb0c585a922f52fa749cceca586886497f24cf2cbad773db436500d4eac695f244a9fa1ad566b741be0b8880b9546357905a3f1311233be"},
				"docker":     {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-26.04-minimal-cloudimg-arm64-docker.qcow2", Digest: "sha512:8c27a812cce12520b25509821a581d966ffc4ddb8b9517f744c49f1a33cf40ed572fb92a86e8d57c12be23d29bda392e6b394c3bb707c94fcf0195cc970d9b64"},
				"containerd": {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-26.04-minimal-cloudimg-arm64-containerd.qcow2", Digest: "sha512:a638e81753aa110f1c4b8e88e6fa17e07345dc85428be93c719bd1ba9a1654b48591936a52d4d7c4f10f61cb7c2e23918555b518c38bc3ee8d0bc82da23df7c0"},
			},
			"amd64": {
				"none":       {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-26.04-minimal-cloudimg-amd64-none.qcow2", Digest: "sha512:c5f347821bb6d19fd4335d02867606ab043a81ca69c7c8e9c72b8eb75b2c019701943beb49e20717be42ed3373e301004a0143ac34ef68da767129d3f1302029"},
				"docker":     {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-26.04-minimal-cloudimg-amd64-docker.qcow2", Digest: "sha512:e3c428c18c3ed02a5675b282830c0830d0fb55465b3ad3967fe67aef6a7fdf60fca97dc1195e044d8e5d89e44716ec907261b5b55514b1e6540267a9809b071d"},
				"containerd": {URL: "https://github.com/olegshirko/docker-mirror/releases/download/master/ubuntu-26.04-minimal-cloudimg-amd64-containerd.qcow2", Digest: "sha512:70c76d73b07c648c10696866fe99b1f91aef677d8cef939be2da85f7512faf84e2459fc5a44dd2710d5711004809b4bcf049f7f0aa66b300d6514f53e719e3d0"},
			},
		},
	},
}
