# Anvil-generated Incus preseed configuration.
cluster: null
projects: []

networks:
  - name: {{.Interface}}
    type: ""
    description: ""
    project: default
    config:
      ipv4.address: 192.100.0.1/24
      ipv4.nat: "true"
      ipv6.address: auto

{{ if .SetStorage }}
storage_pools:
  - name: default
    driver: zfs
    description: ""
    config:
      size: {{.Disk}}GiB
{{ end }}

profiles:
  - name: default
    description: ""
    config: {}
    devices:
      eth0:
        name: eth0
        network: {{.Interface}}
        type: nic
      root:
        name: root
        path: /
        pool: default
        type: disk
