package infra

import (
	"context"
	"fmt"
	"net/url"
	"os/exec"
	gos "runtime"

	"anvil/internal/usecase"
)

// BrowserImageRequester opens a pre-filled browser tab when the user has no API token.
type BrowserImageRequester struct{}

// NewBrowserImageRequester creates a new browser-based requester.
func NewBrowserImageRequester() usecase.ImageRequester {
	return &BrowserImageRequester{}
}

// Request implements usecase.ImageRequester.
func (b *BrowserImageRequester) Request(ctx context.Context, reqType usecase.ImageRequestType, imageRuntime, arch, tag, version string, wait bool) (*usecase.ImageRequestResult, error) {
	var title, body string

	switch reqType {
	case usecase.RequestVMBaseImage:
		title = fmt.Sprintf("[anvil] Request VM base image: ubuntu-%s-minimal-cloudimg-%s-%s.qcow2", version, arch, imageRuntime)
		body = fmt.Sprintf(
			"<!-- anvil-request-image -->\n\n**Request Type:** VM base image\n**Runtime:** %s\n**Arch:** %s\n**Tag:** %s\n\nThis request was generated by anvil (browser fallback).",
			imageRuntime, arch, tag,
		)
	case usecase.RequestDockerImage:
		title = fmt.Sprintf("[anvil] Request Docker image: %s:%s (%s)", imageRuntime, tag, arch)
		body = fmt.Sprintf(
			"<!-- anvil-request-image\n{\"image\":\"%s\",\"tag\":\"%s\",\"platform\":\"%s\"}\n-->\n\n**Request Type:** Docker image\n**Image:** %s\n**Tag:** %s\n**Platform:** %s\n\nThis request was generated by anvil (browser fallback).\n\nThe reconcile workflow will process this issue and pull the image from Docker Hub.",
			imageRuntime, tag, arch,
			imageRuntime, tag, arch,
		)
	default:
		return nil, fmt.Errorf("unknown request type: %s", reqType)
	}

	u := fmt.Sprintf(
		"https://github.com/olegshirko/docker-mirror/issues/new?title=%s&body=%s",
		url.QueryEscape(title),
		url.QueryEscape(body),
	)

	fmt.Println("GITHUB_TOKEN not set. Opening browser to create the issue manually...")
	fmt.Printf("URL: %s\n", u)

	var cmd *exec.Cmd
	switch gos.GOOS {
	case "darwin":
		cmd = exec.CommandContext(ctx, "open", u)
	case "linux":
		cmd = exec.CommandContext(ctx, "xdg-open", u)
	default:
		fmt.Println("Please open the URL manually in your browser.")
		return nil, nil
	}

	if err := cmd.Start(); err != nil {
		fmt.Printf("Could not open browser: %v\n", err)
		fmt.Println("Please open the URL manually.")
	}

	return nil, nil
}
