// M0/M1: boot a Linux VM with Virtualization.framework and control it via
// virtio-vsock guest-agent without SSH.
//
// Build and run ONLY on macOS arm64 (13+) with the Xcode/Swift toolchain.
// Requires the com.apple.security.virtualization entitlement — see Makefile.

import Foundation

// Auto-generated by Makefile: Sources/vz-runner/version.swift
var appVersion = buildVersion

// If this process was spawned by the daemon for a task that must not outlive
// the daemon (e.g. containerd cache sync), exit immediately when the parent
// disappears. This prevents orphan `anvil exec` processes after `kill -9`.
if ProcessInfo.processInfo.environment["ANVIL_EXIT_ON_PARENT_DEATH"] == "1" {
    DispatchQueue.global().async {
        while true {
            Thread.sleep(forTimeInterval: 1.0)
            if getppid() == 1 {
                exit(1)
            }
        }
    }
}

// MARK: - Service helpers

private let daemonPIDFile = stateDir.appendingPathComponent("daemon.pid")
private let prevContextFile = stateDir.appendingPathComponent("previous-docker-context")
private let prevBuilderFile = stateDir.appendingPathComponent("previous-buildx-builder")
private let daemonLogFile = stateDir.appendingPathComponent("daemon.log")

func isDaemonRunning() -> Bool {
    guard let data = try? Data(contentsOf: daemonPIDFile),
          let s = String(data: data, encoding: .utf8),
          let pid = Int32(s.trimmingCharacters(in: .whitespacesAndNewlines)) else {
        return false
    }
    return kill(pid, 0) == 0
}

func saveDockerContext() {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = ["docker", "context", "show"]
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    try? proc.run()
    proc.waitUntilExit()
    let ctx = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
        .trimmingCharacters(in: .whitespacesAndNewlines) ?? "default"
    if ctx != "anvil" {
        try? ctx.write(toFile: prevContextFile.path, atomically: true, encoding: .utf8)
    } else {
        try? FileManager.default.removeItem(at: prevContextFile)
    }
}

func restoreDockerContext() {
    let current = shell("docker", "context", "show").trimmingCharacters(in: .whitespacesAndNewlines)
    guard current == "anvil-remote" else { return }
    let target: String
    if let ctx = try? String(contentsOf: prevContextFile, encoding: .utf8).trimmingCharacters(in: .whitespacesAndNewlines),
       !ctx.isEmpty {
        target = ctx
    } else {
        target = "default"
    }
    _ = shell("docker", "context", "use", target)
    try? FileManager.default.removeItem(at: prevContextFile)
    restoreBuildxBuilder()
}

// MARK: - buildx integration

func currentBuildxBuilder() -> String {
    // `docker buildx inspect` without arguments shows the active builder.
    let out = shell("docker", "buildx", "inspect")
    for line in out.split(separator: "\n") {
        let t = line.trimmingCharacters(in: .whitespaces)
        if t.hasPrefix("Name:") {
            return String(t.dropFirst("Name:".count)).trimmingCharacters(in: .whitespaces)
        }
    }
    return "default"
}

// Point buildx at the buildkitd instance inside the VM through the remote
// driver, so plain `docker build` works without DOCKER_BUILDKIT=0. The
// previously selected builder is saved and restored on `anvil stop`.
func setupBuildxBuilder() {
    guard !shell("docker", "buildx", "version").isEmpty else { return }
    let current = currentBuildxBuilder()
    if current != "anvil-remote" {
        try? current.write(toFile: prevBuilderFile.path, atomically: true, encoding: .utf8)
    }
    let inspect = shell("docker", "buildx", "inspect", "anvil-remote")
    if inspect.isEmpty || !inspect.contains("Driver:") || !inspect.contains("remote") {
        // Missing, or a stale builder with the wrong driver (e.g. an older
        // docker-container one) — recreate it against the buildkit socket.
        _ = shell("docker", "buildx", "rm", "-f", "anvil-remote")
        _ = shell("docker", "buildx", "create", "--name", "anvil-remote",
                  "--driver", "remote", "unix://\(buildkitSocketPath)")
    }
    _ = shell("docker", "buildx", "use", "anvil-remote")
}

func restoreBuildxBuilder() {
    guard currentBuildxBuilder() == "anvil-remote" else { return }
    let saved = (try? String(contentsOf: prevBuilderFile, encoding: .utf8))?
        .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    _ = shell("docker", "buildx", "use", saved.isEmpty ? "default" : saved)
    try? FileManager.default.removeItem(at: prevBuilderFile)
}

func shell(_ args: String...) -> String {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = args
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    try? proc.run()
    proc.waitUntilExit()
    return String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
}

func waitForControlSocket(timeout: TimeInterval = 60, process: Process? = nil) -> Bool {
    let sockPath = controlSocketPath
    let deadline = Date().addingTimeInterval(timeout)
    while Date() < deadline {
        var isDir: ObjCBool = false
        if FileManager.default.fileExists(atPath: sockPath, isDirectory: &isDir), !isDir.boolValue {
            return true
        }
        // The daemon dying before becoming ready (e.g. invalid kernel) would
        // otherwise burn the whole timeout.
        if let process = process, !process.isRunning {
            return false
        }
        Thread.sleep(forTimeInterval: 0.1)
    }
    return false
}

// MARK: - Commands

func cmdStart(args: [String]) {
    if isDaemonRunning() {
        let pid = (try? String(contentsOf: daemonPIDFile, encoding: .utf8))?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "?"
        print("[anvil] daemon already running (pid \(pid))")
        _ = shell("docker", "context", "rm", "-f", "anvil")
        _ = shell("docker", "context", "create", "anvil", "--docker", "host=unix://\(dockerSocketPath)")
        _ = shell("docker", "context", "use", "anvil")
        setupBuildxBuilder()
        return
    }

    let stateBinDir = stateDir.appendingPathComponent("bin")

    let brewAssets = brewAssetsDir()

    // Resolve kernel path: flag > stateDir > brew assets > project root
    var kernelCandidates = [stateDir.appendingPathComponent("vmlinuz-raw").path,
                            stateBinDir.appendingPathComponent("vmlinuz-raw").path]
    if let brewAssets = brewAssets {
        kernelCandidates.append("\(brewAssets)/vmlinuz-raw")
    }
    var kernel = findArg(args, "--kernel")
        ?? findFile(kernelCandidates,
                    fallback: findProjectRoot().map { "\($0)/.download/alpine/vmlinuz-raw" }
                        ?? findProjectRoot().map { "\($0)/.download/ubuntu/vmlinuz-raw" })
    // Releases/bottles ship the kernel gzipped and the service script
    // normally unpacks it; when `anvil start` runs directly (e.g. under
    // zerobrew, which has no services), unpack it ourselves.
    if kernel == nil {
        kernel = unpackBundledKernel(stateDir: stateDir, stateBinDir: stateBinDir, brewAssets: brewAssets)
    }

    // Resolve initrd path: flag > stateDir > brew assets > project root
    var initrdCandidates = [stateDir.appendingPathComponent("initramfs-containerd").path,
                            stateBinDir.appendingPathComponent("initramfs-containerd").path]
    if let brewAssets = brewAssets {
        initrdCandidates.append("\(brewAssets)/initramfs-containerd")
    }
    let initrd = findArg(args, "--initrd")
        ?? findFile(initrdCandidates,
                    fallback: findProjectRoot().map { "\($0)/.download/ubuntu/initramfs-containerd" })

    let share = findArg(args, "--share")
        ?? findProjectRoot().map { "\($0)" }
        ?? stateDir.path
    let memory = findArg(args, "--memory") ?? "2"
    let idle = findArg(args, "--idle") ?? "600"
    let containerdDisk = stateDir.appendingPathComponent("containerd-disk.img").path

    guard let kernelPath = kernel, let initrdPath = initrd else {
        print("[anvil] error: kernel and initrd not found.")
        print("")
        print("  Place them in ~/.anvil-vz/:")
        print("    cp /path/to/vmlinuz-raw      ~/.anvil-vz/vmlinuz-raw")
        print("    cp /path/to/initramfs-containerd ~/.anvil-vz/initramfs-containerd")
        print("")
        print("  Or specify explicitly:")
        print("    anvil start --kernel /path/to/vmlinuz-raw --initrd /path/to/initramfs-containerd")
        exit(1)
    }

    try? FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true)
    // State dir holds the containerd disk (user data) and the sockets;
    // keep it owner-only.
    chmod(stateDir.path, 0o700)
    try? "".write(toFile: daemonLogFile.path, atomically: true, encoding: .utf8)

    // Create the containerd persistent disk if it doesn't exist, or grow it
    // when the target size (ANVIL_DISK_GB, default 64) exceeds the current
    // one. Sparse either way, so the extra capacity costs no host space.
    // Growing changes the file size, which is part of the snapshot config
    // hash — the next boot is a cold boot and stage2 extends the ext4 fs
    // with resize2fs. Never shrink an existing image.
    let diskGB = UInt64(ProcessInfo.processInfo.environment["ANVIL_DISK_GB"] ?? "") ?? 64
    let diskBytes = diskGB * 1024 * 1024 * 1024
    if !FileManager.default.fileExists(atPath: containerdDisk) {
        print("[anvil] creating containerd disk image (\(diskGB) GiB sparse)...")
        FileManager.default.createFile(atPath: containerdDisk, contents: nil)
        chmod(containerdDisk, 0o600)
    }
    if let fh = try? FileHandle(forWritingTo: URL(fileURLWithPath: containerdDisk)) {
        let currentSize = fh.seekToEndOfFile()
        if currentSize < diskBytes {
            print("[anvil] growing containerd disk to \(diskGB) GiB (sparse; next boot is a cold boot)...")
            try? fh.truncate(atOffset: diskBytes)
        }
        try? fh.close()
    }

    saveDockerContext()

    // Build the daemon command line.
    var cmdArgs = [
        "daemon",
        "--kernel", kernelPath,
        "--initrd", initrdPath,
        "--memory", memory,
        "--idle", idle,
    ]
    if !share.isEmpty {
        cmdArgs += ["--share", share]
    }
    if FileManager.default.fileExists(atPath: containerdDisk) {
        cmdArgs += ["--containerd-disk", containerdDisk]
    }

    // Launch the daemon process in the background.
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: currentExecutablePath())
    proc.arguments = cmdArgs
    proc.standardOutput = FileHandle(forWritingAtPath: daemonLogFile.path)
    proc.standardError = proc.standardOutput
    // Detach from the controlling terminal.
    proc.qualityOfService = .background
    do {
        try proc.run()
    } catch {
        print("[anvil] error: failed to launch daemon: \(error)")
        exit(1)
    }
    print("[anvil] starting daemon (pid \(proc.processIdentifier))...")

    // Wait for the control socket to appear; if the daemon dies before
    // becoming ready (e.g. it cannot open the kernel), fail fast with a
    // pointer at the log instead of burning the whole timeout.
    guard waitForControlSocket(process: proc) else {
        if !proc.isRunning {
            print("[anvil] error: daemon exited during startup; see \(daemonLogFile.path)")
        } else {
            print("[anvil] error: daemon did not become ready within 60s")
            proc.terminate()
        }
        exit(1)
    }

    _ = shell("docker", "context", "rm", "-f", "anvil")
    _ = shell("docker", "context", "create", "anvil", "--docker", "host=unix://\(dockerSocketPath)")
    _ = shell("docker", "context", "use", "anvil")
    setupBuildxBuilder()
    print("[anvil] ready (pid \(proc.processIdentifier))")
}

func cmdStop(args: [String]) {
    guard let data = try? Data(contentsOf: daemonPIDFile),
          let s = String(data: data, encoding: .utf8),
          let pid = Int32(s.trimmingCharacters(in: .whitespacesAndNewlines)) else {
        print("[anvil] daemon not running")
        restoreDockerContext()
        return
    }
    guard kill(pid, 0) == 0 else {
        print("[anvil] daemon not running (stale pid file)")
        try? FileManager.default.removeItem(at: daemonPIDFile)
        restoreDockerContext()
        return
    }

    print("[anvil] stopping daemon (pid \(pid))...")
    kill(pid, SIGTERM)

    // Wait for the process to exit.
    let deadline = Date().addingTimeInterval(90)
    while Date() < deadline {
        if kill(pid, 0) != 0 { break }
        Thread.sleep(forTimeInterval: 0.3)
    }
    // Force kill if still alive.
    if kill(pid, 0) == 0 {
        print("[anvil] daemon did not stop gracefully, sending SIGKILL...")
        kill(pid, SIGKILL)
    }

    try? FileManager.default.removeItem(at: daemonPIDFile)
    print("[anvil] daemon stopped")
    restoreDockerContext()
}

func cmdStatus() {
    if isDaemonRunning() {
        let pid = (try? String(contentsOf: daemonPIDFile, encoding: .utf8))?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "?"
        print("[anvil] daemon running (pid \(pid))")
    } else {
        print("[anvil] daemon not running")
        // Non-zero exit so scripts and the bench harness can poll this as a
        // readiness gate; previously status always succeeded.
        exit(1)
    }
    let ctx = shell("docker", "context", "show").trimmingCharacters(in: .whitespacesAndNewlines)
    print("[anvil] docker context: \(ctx)")
    // Query the control socket; exits non-zero until the full chain
    // (daemon -> control server -> guest agent) answers, so scripts and the
    // bench harness can poll `status` as an honest readiness gate.
    ControlClient.status()
}

// MARK: - Arg helpers

func currentExecutablePath() -> String {
    // Bundle.main.executableURL is the most reliable — resolves symlinks.
    if let url = Bundle.main.executableURL {
        return url.path
    }
    // Fallback: resolve CommandLine.arguments[0] through realpath.
    let arg0 = CommandLine.arguments[0]
    if !arg0.isEmpty {
        if arg0.hasPrefix("/") {
            if let cPath = arg0.cString(using: .utf8),
               let resolved = realpath(cPath, nil) {
                return String(cString: resolved)
            }
        } else {
            // Relative or bare name — resolve against CWD, then try PATH.
            let abs = URL(fileURLWithPath: arg0).path
            if let cPath = abs.cString(using: .utf8),
               let resolved = realpath(cPath, nil) {
                return String(cString: resolved)
            }
            // Search PATH for the command name.
            if let pathEnv = ProcessInfo.processInfo.environment["PATH"] {
                for dir in pathEnv.split(separator: ":") {
                    let candidate = "\(dir)/\(arg0)"
                    if FileManager.default.isExecutableFile(atPath: candidate) {
                        return candidate
                    }
                }
            }
        }
    }
    return arg0
}

func findArg(_ args: [String], _ key: String) -> String? {
    guard let idx = args.firstIndex(of: key), idx + 1 < args.count else { return nil }
    return args[idx + 1]
}

func findFile(_ candidates: [String], fallback: String?) -> String? {
    for path in candidates {
        if FileManager.default.isReadableFile(atPath: path) {
            return path
        }
    }
    if let fallback = fallback, FileManager.default.isReadableFile(atPath: fallback) {
        return fallback
    }
    return nil
}

/// Unpack the gzipped kernel shipped in release tarballs/bottles into the
/// state dir. Returns the unpacked path, or nil when no gzipped kernel is
/// available anywhere.
func unpackBundledKernel(stateDir: URL, stateBinDir: URL, brewAssets: String?) -> String? {
    var candidates = [stateDir.appendingPathComponent("vmlinuz-raw.gz").path,
                      stateBinDir.appendingPathComponent("vmlinuz-raw.gz").path]
    if let brewAssets = brewAssets {
        candidates.append("\(brewAssets)/vmlinuz-raw.gz")
    }
    guard let gz = candidates.first(where: { FileManager.default.isReadableFile(atPath: $0) }) else {
        return nil
    }
    let dest = stateDir.appendingPathComponent("vmlinuz-raw").path
    print("[anvil] unpacking bundled kernel \(gz) -> \(dest)")
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/gunzip")
    proc.arguments = ["-c", gz]
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    guard (try? proc.run()) != nil else { return nil }
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    proc.waitUntilExit()
    // gunzip exits 2 on warnings (e.g. "trailing garbage ignored") although
    // the payload decoded fine; only a fully empty output is a real failure.
    guard (proc.terminationStatus == 0 || proc.terminationStatus == 2), !data.isEmpty else { return nil }
    // On a fresh install the state dir does not exist yet (cmdStart creates
    // it later), so create it here; a failed write must not look like success.
    try? FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true)
    guard FileManager.default.createFile(atPath: dest, contents: data) else { return nil }
    chmod(dest, 0o600)
    return dest
}

func findProjectRoot() -> String? {
    // Check current working directory first (user is in the project tree).
    let cwd = FileManager.default.currentDirectoryPath
    if FileManager.default.fileExists(atPath: URL(fileURLWithPath: cwd).appendingPathComponent("Package.swift").path) {
        return cwd
    }
    // Walk up from the executable looking for Package.swift.
    var url = URL(fileURLWithPath: currentExecutablePath()).deletingLastPathComponent()
    for _ in 0..<10 {
        if FileManager.default.fileExists(atPath: url.appendingPathComponent("Package.swift").path) {
            return url.path
        }
        let parent = url.deletingLastPathComponent()
        if parent.path == url.path { break }
        url = parent
    }
    return nil
}

func brewAssetsDir() -> String? {
    // Homebrew installs assets next to the binary:
    // /opt/homebrew/Cellar/anvil/<version>/bin/vz-runner
    //   -> /opt/homebrew/Cellar/anvil/<version>/share/anvil/assets
    let exe = currentExecutablePath()
    let url = URL(fileURLWithPath: exe).deletingLastPathComponent().deletingLastPathComponent()
    let assetsDir = url.appendingPathComponent("share/anvil/assets")
    if FileManager.default.fileExists(atPath: assetsDir.path) {
        return assetsDir.path
    }
    return nil
}

// MARK: - Usage

func printUsage() {
    print("""
    Usage:
      anvil start [--kernel <path>] [--initrd <path>] [--share <path>]
      anvil stop
      anvil restart
      anvil status
      anvil daemon [--kernel <path>] [--initrd <path>] [--share <path>]
      anvil boot --kernel <path> --initrd <path> [--agent]
      anvil exec <command> [args...]
      anvil doctor
      anvil logs [daemon|console|guest]
      anvil images [list|check|request] --docker <image:tag>
      anvil docker-socket-path

    Service commands:
      start     Launch the daemon in the background, wait for ready,
                switch Docker context to "anvil".
      stop      Stop the daemon, restore the previous Docker context.
      restart   Stop + start.
      status    Show daemon status and Docker context.

    Daemon options (start / daemon):
      --kernel <path>   Path to the Linux kernel image (default: .download/ubuntu/vmlinuz-raw)
      --initrd <path>   Path to the initramfs/initrd image (default: .download/ubuntu/initramfs-containerd)
      --share <path>    Share host directory via virtiofs
      --idle <seconds>  Seconds to wait before pausing VM (default: 600)
      --memory <gib>    Memory in GiB (default: 2)

    Boot options:
      --kernel <path>   Path to the Linux kernel image (ARM64 Image format)
      --initrd <path>   Path to the initramfs/initrd image
      --agent           Use rdinit=/myinit (for initramfs with guest-agent)
      --fresh           Force cold boot and recreate snapshot
      --share <path>    Share host directory via virtiofs
      --mount-tag <tag> Virtiofs tag (default: anvil)
      --cpus <n>        Number of CPUs (default: 2)
      --memory <gib>    Memory in GiB (default: 2)
    """)
}

// MARK: - Main

let arguments = Array(CommandLine.arguments.dropFirst())
guard let subcommand = arguments.first else {
    printUsage()
    exit(1)
}

switch subcommand {
case "start":
    cmdStart(args: Array(arguments.dropFirst()))
case "stop":
    cmdStop(args: Array(arguments.dropFirst()))
case "status":
    cmdStatus()
case "restart":
    cmdStop(args: [])
    cmdStart(args: Array(arguments.dropFirst()))
case "daemon":
    DaemonCommand.run(args: Array(arguments.dropFirst()))
case "boot":
    BootCommand.run(args: Array(arguments.dropFirst()))
case "exec":
    let cmdArgs = Array(arguments.dropFirst())
    guard !cmdArgs.isEmpty else {
        printUsage()
        exit(1)
    }
    ControlClient.exec(command: cmdArgs)
case "doctor":
    cmdDoctor()
case "logs":
    cmdLogs(args: Array(arguments.dropFirst()))
case "images":
    cmdImages(args: Array(arguments.dropFirst()))
case "docker-socket-path":
    print(dockerSocketPath)
    exit(0)
case "--help", "-h":
    printUsage()
    exit(0)
default:
    printUsage()
    exit(1)
}
