// M0/M1: boot a Linux VM with Virtualization.framework and control it via
// virtio-vsock guest-agent without SSH.
//
// Build and run ONLY on macOS arm64 (13+) with the Xcode/Swift toolchain.
// Requires the com.apple.security.virtualization entitlement — see Makefile.

import Foundation

// Auto-generated by Makefile: Sources/vz-runner/version.swift
var appVersion = buildVersion

// If this process was spawned by the daemon for a task that must not outlive
// the daemon (e.g. containerd cache sync), exit immediately when the parent
// disappears. This prevents orphan `anvil exec` processes after `kill -9`.
if ProcessInfo.processInfo.environment["ANVIL_EXIT_ON_PARENT_DEATH"] == "1" {
    DispatchQueue.global().async {
        while true {
            Thread.sleep(forTimeInterval: 1.0)
            if getppid() == 1 {
                exit(1)
            }
        }
    }
}

// MARK: - Service helpers

private let daemonPIDFile = stateDir.appendingPathComponent("daemon.pid")
private let prevContextFile = stateDir.appendingPathComponent("previous-docker-context")
private let prevBuilderFile = stateDir.appendingPathComponent("previous-buildx-builder")
private let daemonLogFile = stateDir.appendingPathComponent("daemon.log")

func isDaemonRunning() -> Bool {
    guard let data = try? Data(contentsOf: daemonPIDFile),
          let s = String(data: data, encoding: .utf8),
          let pid = Int32(s.trimmingCharacters(in: .whitespacesAndNewlines)) else {
        return false
    }
    return kill(pid, 0) == 0 && isAnvilProcess(pid)
}

func daemonPID() -> Int32? {
    guard let s = try? String(contentsOf: daemonPIDFile, encoding: .utf8) else { return nil }
    return Int32(s.trimmingCharacters(in: .whitespacesAndNewlines))
}

func executablePath(of pid: Int32) -> String? {
    var buf = [CChar](repeating: 0, count: 4 * Int(MAXPATHLEN))
    guard proc_pidpath(pid, &buf, UInt32(buf.count)) > 0 else { return nil }
    return String(cString: buf)
}

/// Whether pid runs an anvil binary. A pid file left by a daemon that died
/// with the Mac (power loss, SIGKILL at logout) can name a reused pid; such
/// a process must neither block a start nor receive our signals.
func isAnvilProcess(_ pid: Int32) -> Bool {
    // Not inspectable (another user's process): not anvil.
    guard let path = executablePath(of: pid) else { return false }
    let name = (path as NSString).lastPathComponent
    return name == "vz-runner" || name == "anvil"
}

func saveDockerContext() {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = ["docker", "context", "show"]
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    try? proc.run()
    proc.waitUntilExit()
    let ctx = String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8)?
        .trimmingCharacters(in: .whitespacesAndNewlines) ?? "default"
    // Already on anvil (a daemon that died without a stop left it there):
    // keep the context saved back then, or stop would fall back to default.
    if ctx != dockerContextName {
        try? ctx.write(toFile: prevContextFile.path, atomically: true, encoding: .utf8)
    }
}

/// The buildx builder pointing at this instance's buildkit socket.
let buildxBuilderName = dockerContextName + "-remote"

/// (Re)creates this instance's docker context. The usual instance also
/// makes it current; a named one (ANVIL_INSTANCE=dev) leaves the user's
/// context alone — use `docker --context anvil-dev` or DOCKER_CONTEXT.
func registerDockerContext() {
    _ = shell("docker", "context", "rm", "-f", dockerContextName)
    _ = shell("docker", "context", "create", dockerContextName, "--docker", "host=unix://\(dockerSocketPath)")
    if anvilInstance.isEmpty {
        _ = shell("docker", "context", "use", dockerContextName)
    } else {
        print("[anvil] instance \(anvilInstance): docker context \(dockerContextName) (not made current; use `docker --context \(dockerContextName)` or DOCKER_CONTEXT=\(dockerContextName))")
    }
}

func restoreDockerContext() {
    let current = shell("docker", "context", "show").trimmingCharacters(in: .whitespacesAndNewlines)
    guard current == dockerContextName else { return }
    // buildx keeps its selected builder per context: put the previous one
    // back while anvil's context is still current.
    restoreBuildxBuilder()
    let target: String
    if let ctx = try? String(contentsOf: prevContextFile, encoding: .utf8).trimmingCharacters(in: .whitespacesAndNewlines),
       !ctx.isEmpty {
        target = ctx
    } else {
        target = "default"
    }
    _ = shell("docker", "context", "use", target)
    try? FileManager.default.removeItem(at: prevContextFile)
}

// MARK: - buildx integration

func currentBuildxBuilder() -> String {
    // `docker buildx inspect` without arguments shows the active builder.
    let out = shell("docker", "buildx", "inspect")
    for line in out.split(separator: "\n") {
        let t = line.trimmingCharacters(in: .whitespaces)
        if t.hasPrefix("Name:") {
            return String(t.dropFirst("Name:".count)).trimmingCharacters(in: .whitespaces)
        }
    }
    return "default"
}

// Point buildx at the buildkitd instance inside the VM through the remote
// driver, so plain `docker build` works without DOCKER_BUILDKIT=0. The
// previously selected builder is saved and restored on `anvil stop`.
func setupBuildxBuilder() {
    guard !shell("docker", "buildx", "version").isEmpty else { return }
    let current = currentBuildxBuilder()
    if current != buildxBuilderName {
        try? current.write(toFile: prevBuilderFile.path, atomically: true, encoding: .utf8)
    }
    let inspect = shell("docker", "buildx", "inspect", buildxBuilderName)
    if inspect.isEmpty || !inspect.contains("Driver:") || !inspect.contains("remote") {
        // Missing, or a stale builder with the wrong driver (e.g. an older
        // docker-container one) — recreate it against the buildkit socket.
        _ = shell("docker", "buildx", "rm", "-f", buildxBuilderName)
        _ = shell("docker", "buildx", "create", "--name", buildxBuilderName,
                  "--driver", "remote", "unix://\(buildkitSocketPath)")
    }
    if anvilInstance.isEmpty {
        _ = shell("docker", "buildx", "use", buildxBuilderName)
    }
}

func restoreBuildxBuilder() {
    guard currentBuildxBuilder() == buildxBuilderName else { return }
    let saved = (try? String(contentsOf: prevBuilderFile, encoding: .utf8))?
        .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    _ = shell("docker", "buildx", "use", saved.isEmpty ? "default" : saved)
    try? FileManager.default.removeItem(at: prevBuilderFile)
}

// setupBuildxBuilderAsync launches the buildx setup as a detached child
// process (the internal `_setup-buildx` subcommand) so `anvil start` does not
// block on the 5-8 slow docker/buildx calls. The child ignores SIGHUP so a
// terminal hangup during the ~2s window does not abort it. On any failure to
// spawn, it falls back to a synchronous setup.
func setupBuildxBuilderAsync() {
    // Disown via nohup + `&` so the child survives the parent and terminal
    // hangups during the ~2s window the buildx dance takes.
    let wrapper = Process()
    wrapper.executableURL = URL(fileURLWithPath: "/bin/sh")
    wrapper.arguments = ["-c", "nohup \"\(currentExecutablePath())\" _setup-buildx >/dev/null 2>&1 &"]
    wrapper.standardOutput = FileHandle.nullDevice
    wrapper.standardError = FileHandle.nullDevice
    do {
        try wrapper.run()
    } catch {
        // Fallback: synchronous, so buildx still gets configured.
        setupBuildxBuilder()
    }
}

func shell(_ args: String...) -> String {
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    proc.arguments = args
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    try? proc.run()
    proc.waitUntilExit()
    return String(data: pipe.fileHandleForReading.readDataToEndOfFile(), encoding: .utf8) ?? ""
}

func waitForControlSocket(timeout: TimeInterval = 60, process: Process? = nil) -> Bool {
    let sockPath = controlSocketPath
    let deadline = Date().addingTimeInterval(timeout)
    while Date() < deadline {
        var isDir: ObjCBool = false
        if FileManager.default.fileExists(atPath: sockPath, isDirectory: &isDir), !isDir.boolValue {
            return true
        }
        // The daemon dying before becoming ready (e.g. invalid kernel) would
        // otherwise burn the whole timeout.
        if let process = process, !process.isRunning {
            return false
        }
        Thread.sleep(forTimeInterval: 0.1)
    }
    return false
}

// MARK: - Commands

func cmdStart(args: [String]) {
    // After an upgrade the old daemon keeps running the old binary (and, for
    // Homebrew, assets of a keg the upgrade deletes): restart it, as the
    // service wrapper does.
    if isDaemonRunning(), let pid = daemonPID(), let running = executablePath(of: pid),
       URL(fileURLWithPath: running).resolvingSymlinksInPath().path
        != URL(fileURLWithPath: currentExecutablePath()).resolvingSymlinksInPath().path {
        print("[anvil] daemon runs another binary (\(running)); restarting it")
        cmdStop(args: [])
    }
    if isDaemonRunning() {
        let pid = (try? String(contentsOf: daemonPIDFile, encoding: .utf8))?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "?"
        print("[anvil] daemon already running (pid \(pid))")
        registerDockerContext()
        setupBuildxBuilderAsync()
        return
    }

    let stateBinDir = stateDir.appendingPathComponent("bin")

    let brewAssets = brewAssetsDir()

    // Same order as anvil-service.sh: a source tree's fresh build first;
    // otherwise the installed package's assets before state-dir copies, so a
    // stale ~/.anvil-vz kernel or initramfs never shadows an upgrade.
    let projectRoot = findProjectRoot()
    if findArg(args, "--kernel") == nil, projectRoot == nil {
        refreshUnpackedKernel(stateDir: stateDir, stateBinDir: stateBinDir, brewAssets: brewAssets)
    }
    let assets = bootAssetCandidates(stateDir: stateDir.path, stateBinDir: stateBinDir.path,
                                     brewAssets: brewAssets, projectRoot: projectRoot)
    let kernel = findArg(args, "--kernel") ?? findFile(assets.kernels, fallback: nil)
    let initrd = findArg(args, "--initrd") ?? findFile(assets.initrds, fallback: nil)

    let share = findArg(args, "--share")
        ?? findProjectRoot().map { "\($0)" }
        ?? stateDir.path
    // Flags, then ANVIL_* from the environment or ~/.anvil-vz/config — the
    // service wrapper reads the same settings, so switching between the two
    // start paths keeps the snapshot hash (and skips a cold boot).
    let memory = findArg(args, "--memory") ?? anvilSetting("ANVIL_MEMORY") ?? "2"
    let idle = findArg(args, "--idle") ?? anvilSetting("ANVIL_IDLE") ?? "600"
    let cpus = findArg(args, "--cpus") ?? anvilSetting("ANVIL_CPUS")
    let containerdDisk = stateDir.appendingPathComponent("containerd-disk.img").path

    guard let kernelPath = kernel, let initrdPath = initrd else {
        print("[anvil] error: kernel and initrd not found.")
        print("")
        print("  Place them in ~/.anvil-vz/:")
        print("    cp /path/to/vmlinuz-raw      ~/.anvil-vz/vmlinuz-raw")
        print("    cp /path/to/initramfs-containerd ~/.anvil-vz/initramfs-containerd")
        print("")
        print("  Or specify explicitly:")
        print("    anvil start --kernel /path/to/vmlinuz-raw --initrd /path/to/initramfs-containerd")
        exit(1)
    }

    try? FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true)
    // State dir holds the containerd disk (user data) and the sockets;
    // keep it owner-only.
    chmod(stateDir.path, 0o700)
    // Appended across starts (the previous run's crash stays readable),
    // bounded like the service wrapper's: 10 MB, one old copy.
    if let size = (try? FileManager.default.attributesOfItem(atPath: daemonLogFile.path))?[.size] as? Int,
       size > 10 << 20 {
        try? FileManager.default.removeItem(atPath: daemonLogFile.path + ".1")
        try? FileManager.default.moveItem(atPath: daemonLogFile.path, toPath: daemonLogFile.path + ".1")
    }
    if !FileManager.default.fileExists(atPath: daemonLogFile.path) {
        FileManager.default.createFile(atPath: daemonLogFile.path, contents: nil)
    }

    // Create the containerd persistent disk if it doesn't exist, or grow it
    // when the target size (ANVIL_DISK_GB, default 64) exceeds the current
    // one. Sparse either way, so the extra capacity costs no host space.
    // Growing changes the file size, which is part of the snapshot config
    // hash — the next boot is a cold boot and stage2 extends the ext4 fs
    // with resize2fs. Never shrink an existing image.
    let diskGB = UInt64(anvilSetting("ANVIL_DISK_GB") ?? "") ?? 64
    let diskBytes = diskGB * 1024 * 1024 * 1024
    if !FileManager.default.fileExists(atPath: containerdDisk) {
        print("[anvil] creating containerd disk image (\(diskGB) GiB sparse)...")
        FileManager.default.createFile(atPath: containerdDisk, contents: nil)
        chmod(containerdDisk, 0o600)
    }
    if let fh = try? FileHandle(forWritingTo: URL(fileURLWithPath: containerdDisk)) {
        let currentSize = fh.seekToEndOfFile()
        if currentSize < diskBytes {
            print("[anvil] growing containerd disk to \(diskGB) GiB (sparse; next boot is a cold boot)...")
            try? fh.truncate(atOffset: diskBytes)
        }
        try? fh.close()
    }

    saveDockerContext()

    // Build the daemon command line.
    var cmdArgs = [
        "daemon",
        "--kernel", kernelPath,
        "--initrd", initrdPath,
        "--memory", memory,
        "--idle", idle,
    ]
    if let cpus = cpus, !cpus.isEmpty {
        cmdArgs += ["--cpus", cpus]
    }
    if !share.isEmpty {
        cmdArgs += ["--share", share]
    }
    if FileManager.default.fileExists(atPath: containerdDisk) {
        cmdArgs += ["--containerd-disk", containerdDisk]
    }

    // Launch the daemon process in the background.
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: currentExecutablePath())
    proc.arguments = cmdArgs
    let logHandle = FileHandle(forWritingAtPath: daemonLogFile.path)
    logHandle?.seekToEndOfFile()
    proc.standardOutput = logHandle
    proc.standardError = proc.standardOutput
    do {
        try proc.run()
    } catch {
        print("[anvil] error: failed to launch daemon: \(error)")
        exit(1)
    }
    print("[anvil] starting daemon (pid \(proc.processIdentifier))...")

    // Wait for the control socket to appear; if the daemon dies before
    // becoming ready (e.g. it cannot open the kernel), fail fast with a
    // pointer at the log instead of burning the whole timeout.
    guard waitForControlSocket(process: proc) else {
        if !proc.isRunning {
            print("[anvil] error: daemon exited during startup; see \(daemonLogFile.path)")
        } else {
            print("[anvil] error: daemon did not become ready within 60s")
            proc.terminate()
        }
        exit(1)
    }

    registerDockerContext()
    // buildx setup talks to docker/buildx 5-8 times (~3-4s with Docker Desktop
    // installed) and is only needed for `docker buildx build` — plain `docker
    // build` goes through the guest-agent /build endpoint. Run it detached so
    // `anvil start` returns immediately; buildx is ready a couple seconds later.
    setupBuildxBuilderAsync()
    print("[anvil] ready (pid \(proc.processIdentifier))")
}

func cmdStop(args: [String]) {
    guard let data = try? Data(contentsOf: daemonPIDFile),
          let s = String(data: data, encoding: .utf8),
          let pid = Int32(s.trimmingCharacters(in: .whitespacesAndNewlines)) else {
        print("[anvil] daemon not running")
        restoreDockerContext()
        return
    }
    guard kill(pid, 0) == 0, isAnvilProcess(pid) else {
        print("[anvil] daemon not running (stale pid file)")
        try? FileManager.default.removeItem(at: daemonPIDFile)
        restoreDockerContext()
        return
    }

    print("[anvil] stopping daemon (pid \(pid))...")
    kill(pid, SIGTERM)

    // Wait for the process to exit.
    let deadline = Date().addingTimeInterval(90)
    while Date() < deadline {
        if kill(pid, 0) != 0 { break }
        Thread.sleep(forTimeInterval: 0.3)
    }
    // Force kill if still alive.
    if kill(pid, 0) == 0 {
        print("[anvil] daemon did not stop gracefully, sending SIGKILL...")
        kill(pid, SIGKILL)
    }

    try? FileManager.default.removeItem(at: daemonPIDFile)
    print("[anvil] daemon stopped")
    restoreDockerContext()
}

func cmdStatus() {
    if isDaemonRunning() {
        let pid = (try? String(contentsOf: daemonPIDFile, encoding: .utf8))?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "?"
        print("[anvil] daemon running (pid \(pid))")
    } else {
        print("[anvil] daemon not running")
        // Non-zero exit so scripts and the bench harness can poll this as a
        // readiness gate; previously status always succeeded.
        exit(1)
    }
    // Query the control socket first; exits non-zero until the full chain
    // (daemon -> control server -> guest agent) answers, so scripts and the
    // bench harness can poll `status` as an honest readiness gate. The
    // docker-context print is cosmetic, shells out to the docker CLI
    // (~100-300 ms) and only makes sense for a human at a terminal — skip it
    // when stdout is not a TTY (bench harness, scripts).
    ControlClient.status()
    // A running VM is not a usable daemon without its Docker socket (a lost
    // docker.sock once went unnoticed behind "VM status=ok").
    var st = stat()
    guard stat(dockerSocketPath, &st) == 0, (st.st_mode & S_IFMT) == S_IFSOCK else {
        print("[anvil] docker socket missing: \(dockerSocketPath) (restart the daemon)")
        exit(1)
    }
    if isatty(STDOUT_FILENO) == 1 {
        let ctx = shell("docker", "context", "show").trimmingCharacters(in: .whitespacesAndNewlines)
        print("[anvil] docker context: \(ctx)")
    }
}

// MARK: - Arg helpers

func currentExecutablePath() -> String {
    // Bundle.main.executableURL is the most reliable — resolves symlinks.
    if let url = Bundle.main.executableURL {
        return url.path
    }
    // Fallback: resolve CommandLine.arguments[0] through realpath.
    let arg0 = CommandLine.arguments[0]
    if !arg0.isEmpty {
        if arg0.hasPrefix("/") {
            if let cPath = arg0.cString(using: .utf8),
               let resolved = realpath(cPath, nil) {
                return String(cString: resolved)
            }
        } else {
            // Relative or bare name — resolve against CWD, then try PATH.
            let abs = URL(fileURLWithPath: arg0).path
            if let cPath = abs.cString(using: .utf8),
               let resolved = realpath(cPath, nil) {
                return String(cString: resolved)
            }
            // Search PATH for the command name.
            if let pathEnv = ProcessInfo.processInfo.environment["PATH"] {
                for dir in pathEnv.split(separator: ":") {
                    let candidate = "\(dir)/\(arg0)"
                    if FileManager.default.isExecutableFile(atPath: candidate) {
                        return candidate
                    }
                }
            }
        }
    }
    return arg0
}

func findArg(_ args: [String], _ key: String) -> String? {
    guard let idx = args.firstIndex(of: key), idx + 1 < args.count else { return nil }
    return args[idx + 1]
}

func findFile(_ candidates: [String], fallback: String?) -> String? {
    for path in candidates {
        if FileManager.default.isReadableFile(atPath: path) {
            return path
        }
    }
    if let fallback = fallback, FileManager.default.isReadableFile(atPath: fallback) {
        return fallback
    }
    return nil
}

/// Unpack the gzipped kernel shipped in release tarballs/bottles into the
/// state dir. Returns the unpacked path, or nil when no gzipped kernel is
/// available anywhere.
/// Candidate boot assets in priority order (see cmdStart).
func bootAssetCandidates(stateDir: String, stateBinDir: String, brewAssets: String?,
                         projectRoot: String?) -> (kernels: [String], initrds: [String]) {
    let stateK = ["\(stateDir)/vmlinuz-raw", "\(stateBinDir)/vmlinuz-raw"]
    let stateI = ["\(stateDir)/initramfs-containerd", "\(stateBinDir)/initramfs-containerd"]
    let brewK = brewAssets.map { ["\($0)/vmlinuz-raw"] } ?? []
    let brewI = brewAssets.map { ["\($0)/initramfs-containerd"] } ?? []
    if let root = projectRoot {
        return (["\(root)/.download/alpine/vmlinuz-raw", "\(root)/.download/ubuntu/vmlinuz-raw"] + stateK + brewK,
                ["\(root)/.download/ubuntu/initramfs-containerd"] + stateI + brewI)
    }
    return (brewK + stateK, brewI + stateI)
}

/// Releases ship the kernel gzipped; unpack it into the state dir when the
/// packaged copy is newer than the unpacked one (first start, or an upgrade
/// — the old unpacked kernel would otherwise boot with the new initramfs).
func refreshUnpackedKernel(stateDir: URL, stateBinDir: URL, brewAssets: String?) {
    var candidates = [stateDir.appendingPathComponent("vmlinuz-raw.gz").path,
                      stateBinDir.appendingPathComponent("vmlinuz-raw.gz").path]
    if let brewAssets = brewAssets {
        candidates.insert("\(brewAssets)/vmlinuz-raw.gz", at: 0)
    }
    guard let gz = candidates.first(where: { FileManager.default.isReadableFile(atPath: $0) }) else {
        return
    }
    let dest = stateDir.appendingPathComponent("vmlinuz-raw").path
    if let gzDate = modificationDate(gz), let destDate = modificationDate(dest), destDate >= gzDate {
        return
    }
    print("[anvil] unpacking bundled kernel \(gz) -> \(dest)")
    let proc = Process()
    proc.executableURL = URL(fileURLWithPath: "/usr/bin/gunzip")
    proc.arguments = ["-c", gz]
    let pipe = Pipe()
    proc.standardOutput = pipe
    proc.standardError = FileHandle.nullDevice
    guard (try? proc.run()) != nil else { return }
    let data = pipe.fileHandleForReading.readDataToEndOfFile()
    proc.waitUntilExit()
    // gunzip exits 2 on warnings (e.g. "trailing garbage ignored") although
    // the payload decoded fine; only a fully empty output is a real failure.
    guard (proc.terminationStatus == 0 || proc.terminationStatus == 2), !data.isEmpty else { return }
    try? FileManager.default.createDirectory(at: stateDir, withIntermediateDirectories: true)
    if FileManager.default.createFile(atPath: dest, contents: data) {
        chmod(dest, 0o600)
    }
}

private func modificationDate(_ path: String) -> Date? {
    (try? FileManager.default.attributesOfItem(atPath: path))?[.modificationDate] as? Date
}

/// An ANVIL_* setting: the environment wins, then ~/.anvil-vz/config
/// (KEY=VALUE lines), which the LaunchAgent-started service reads as well.
func anvilSetting(_ key: String) -> String? {
    if let v = ProcessInfo.processInfo.environment[key], !v.isEmpty {
        return v
    }
    return parseAnvilConfig(
        (try? String(contentsOf: stateDir.appendingPathComponent("config"), encoding: .utf8)) ?? "")[key]
}

/// Parses KEY=VALUE lines (# comments, optional quotes, `export` prefix).
func parseAnvilConfig(_ text: String) -> [String: String] {
    var out: [String: String] = [:]
    for raw in text.split(separator: "\n") {
        var line = raw.trimmingCharacters(in: .whitespaces)
        if line.isEmpty || line.hasPrefix("#") { continue }
        if line.hasPrefix("export ") { line = String(line.dropFirst(7)) }
        guard let eq = line.firstIndex(of: "=") else { continue }
        let key = line[..<eq].trimmingCharacters(in: .whitespaces)
        var value = line[line.index(after: eq)...].trimmingCharacters(in: .whitespaces)
        if value.count >= 2, let f = value.first, f == "\"" || f == "'", value.last == f {
            value = String(value.dropFirst().dropLast())
        }
        if !key.isEmpty { out[key] = value }
    }
    return out
}

/// An anvil source tree, not just any SwiftPM package: running `anvil
/// start` inside another Swift project made that directory the VM share.
func isAnvilSourceTree(_ dir: URL) -> Bool {
    let fm = FileManager.default
    return fm.fileExists(atPath: dir.appendingPathComponent("Package.swift").path)
        && fm.fileExists(atPath: dir.appendingPathComponent("scripts/anvil-service.sh").path)
        && fm.fileExists(atPath: dir.appendingPathComponent("guest-agent/go.mod").path)
}

func findProjectRoot() -> String? {
    // Check current working directory first (user is in the project tree).
    let cwd = FileManager.default.currentDirectoryPath
    if isAnvilSourceTree(URL(fileURLWithPath: cwd)) {
        return cwd
    }
    // Walk up from the executable looking for the source tree.
    var url = URL(fileURLWithPath: currentExecutablePath()).deletingLastPathComponent()
    for _ in 0..<10 {
        if isAnvilSourceTree(url) {
            return url.path
        }
        let parent = url.deletingLastPathComponent()
        if parent.path == url.path { break }
        url = parent
    }
    return nil
}

func brewAssetsDir() -> String? {
    // Homebrew installs assets next to the binary:
    // /opt/homebrew/Cellar/anvil/<version>/bin/vz-runner
    //   -> /opt/homebrew/Cellar/anvil/<version>/share/anvil/assets
    let exe = currentExecutablePath()
    let url = URL(fileURLWithPath: exe).deletingLastPathComponent().deletingLastPathComponent()
    // Prefer the version-independent <prefix>/opt/<formula> link: `brew
    // upgrade` deletes the old keg, and a daemon restarted after a crash
    // would look for its kernel there.
    let parts = url.pathComponents
    if let cellar = parts.firstIndex(of: "Cellar"), cellar + 1 < parts.count {
        let prefix = NSString.path(withComponents: Array(parts[..<cellar]))
        let opt = URL(fileURLWithPath: prefix).appendingPathComponent("opt")
            .appendingPathComponent(parts[cellar + 1]).appendingPathComponent("share/anvil/assets")
        if FileManager.default.fileExists(atPath: opt.path) {
            return opt.path
        }
    }
    let assetsDir = url.appendingPathComponent("share/anvil/assets")
    if FileManager.default.fileExists(atPath: assetsDir.path) {
        return assetsDir.path
    }
    return nil
}

// MARK: - Usage

func printUsage() {
    print("""
    Usage:
      anvil start [--kernel <path>] [--initrd <path>] [--share <path>]
      anvil stop
      anvil restart
      anvil status
      anvil daemon [--kernel <path>] [--initrd <path>] [--share <path>]
      anvil boot --kernel <path> --initrd <path> [--agent]
      anvil exec <command> [args...]
      anvil doctor
      anvil logs [daemon|console|guest]
      anvil images [list|check|request] --docker <image:tag>
      anvil prune [-f]          remove all containers, unused images, volumes, build cache
      anvil disk-compact        give freed containerd disk space back to macOS (stops the daemon)
      anvil docker-socket-path
      anvil --version

    Service commands:
      start     Launch the daemon in the background, wait for ready,
                switch Docker context to "anvil".
      stop      Stop the daemon, restore the previous Docker context.
      restart   Stop + start.
      status    Show daemon status and Docker context.

    Daemon options (start / daemon):
      --kernel <path>   Path to the Linux kernel image (default: .download/alpine/vmlinuz-raw)
      --initrd <path>   Path to the initramfs/initrd image (default: .download/ubuntu/initramfs-containerd)
      --share <path>    Share host directory via virtiofs
      --idle <seconds>  Seconds to wait before pausing VM (default: 600)
      --memory <gib>    Memory in GiB (default: 2)

    Boot options:
      --kernel <path>   Path to the Linux kernel image (ARM64 Image format)
      --initrd <path>   Path to the initramfs/initrd image
      --agent           Use rdinit=/myinit (for initramfs with guest-agent)
      --fresh           Force cold boot and recreate snapshot
      --share <path>    Share host directory via virtiofs
      --mount-tag <tag> Virtiofs tag (default: anvil)
      --cpus <n>        Number of CPUs (default: 2)
      --memory <gib>    Memory in GiB (default: 2)
    """)
}

// MARK: - Main

// Line-buffer stdout: the daemon redirects it to a log file, and block
// buffering there hides the ordering of port-forwarder lifecycle messages
// exactly when they are needed to diagnose a stale listener.
setvbuf(stdout, nil, _IOLBF, 0)

let arguments = Array(CommandLine.arguments.dropFirst())
guard let subcommand = arguments.first else {
    printUsage()
    exit(1)
}

switch subcommand {
case "start":
    cmdStart(args: Array(arguments.dropFirst()))
case "stop":
    cmdStop(args: Array(arguments.dropFirst()))
case "status":
    cmdStatus()
case "restart":
    cmdStop(args: [])
    cmdStart(args: Array(arguments.dropFirst()))
case "daemon":
    DaemonCommand.run(args: Array(arguments.dropFirst()))
case "boot":
    BootCommand.run(args: Array(arguments.dropFirst()))
case "exec":
    let cmdArgs = Array(arguments.dropFirst())
    guard !cmdArgs.isEmpty else {
        printUsage()
        exit(1)
    }
    ControlClient.exec(command: cmdArgs)
case "doctor":
    cmdDoctor(args: Array(arguments.dropFirst()))
case "logs":
    cmdLogs(args: Array(arguments.dropFirst()))
case "images":
    cmdImages(args: Array(arguments.dropFirst()))
case "prune":
    cmdPrune(args: Array(arguments.dropFirst()))
case "disk-compact":
    cmdDiskCompact()
case "docker-socket-path":
    print(dockerSocketPath)
    exit(0)
case "_setup-buildx":
    // Internal, detached: invoked by setupBuildxBuilderAsync so `anvil start`
    // does not block on slow docker/buildx calls. Ignore SIGHUP to survive a
    // terminal hangup during the ~2s the buildx setup takes.
    signal(SIGHUP, SIG_IGN)
    setupBuildxBuilder()
    exit(0)
case "--version", "-v":
    print(appVersion)
    exit(0)
case "--help", "-h":
    printUsage()
    exit(0)
default:
    printUsage()
    exit(1)
}
