package lima

import (
	"bytes"
	"fmt"
	"strings"

	"anvil/internal/domain"
	"anvil/internal/environment/vm/lima/limautil"
)

const (
	localhostAddr         = "127.0.0.1"
	defaultGatewayAddress = "192.168.5.2"
)

var publicDNS = []string{"8.8.8.8", "1.1.1.1"}

func hasDnsmasq(l *limaVM) bool {
	// check if dnsmasq is installed
	return l.RunQuiet("sh", "-c", `apt list 2>/dev/null | grep 'dnsmasq\/' | grep '\[installed'`) == nil
}

func hasSystemdResolved(l *limaVM) bool {
	return l.RunQuiet("sh", "-c", `test -L /etc/resolv.conf && readlink /etc/resolv.conf | grep -q systemd`) == nil
}

func (l *limaVM) setupDNS(conf domain.Config) error {
	// use custom gateway address
	var gatewayAddr = defaultGatewayAddress
	customGatewayAddress := conf.Network.GatewayAddress
	if customGatewayAddress != nil {
		gatewayAddr = customGatewayAddress.String()
	}

	// Build upstream DNS list. When the user hasn't specified custom resolvers,
	// add public DNS servers alongside the Lima gateway so that if Lima's host
	// resolver (gvproxy) times out or drops UDP packets, public DNS can still
	// answer the query.
	var dnsServers []string
	if len(conf.Network.DNSResolvers) > 0 {
		for _, dns := range conf.Network.DNSResolvers {
			dnsServers = append(dnsServers, dns.String())
		}
	} else {
		dnsServers = append([]string{gatewayAddr}, publicDNS...)
	}

	if hasDnsmasq(l) {
		return l.setupDnsmasq(conf, gatewayAddr, dnsServers)
	}

	if hasSystemdResolved(l) {
		return l.setupSystemdResolved(dnsServers)
	}

	// Last resort: write resolv.conf directly.
	return l.writeResolvConf(dnsServers)
}

func (l *limaVM) setupDnsmasq(conf domain.Config, gatewayAddr string, dnsServers []string) error {
	var dnsHosts = map[string]string{
		"host.docker.internal": gatewayAddr,
		"host.lima.internal":   gatewayAddr,
	}

	internalIP := limautil.NewNetworkInspector(l.configService.Profile().ID).InternalIP()
	if internalIP == "" {
		return fmt.Errorf("failed to determine internal IP address for dnsmasq")
	}

	// extra dns entries
	dnsHosts["anvil.internal"] = internalIP
	if conf.Hostname != "" {
		dnsHosts[conf.Hostname] = localhostAddr
	}

	var buf bytes.Buffer

	// generate dns hosts
	fmt.Fprintln(&buf, "# Generated by anvil")
	fmt.Fprintln(&buf, "# Do not edit this file manually")
	fmt.Fprintln(&buf)
	for k, v := range dnsHosts {
		fmt.Fprintf(&buf, "address=/%s/%s", k, v)
		fmt.Fprintln(&buf)
	}
	fmt.Fprintln(&buf) // for cleaner output

	// generate dns servers
	for _, dns := range dnsServers {
		fmt.Fprintf(&buf, "server=%s", dns)
		fmt.Fprintln(&buf)
	}
	fmt.Fprintln(&buf) // for cleaner output

	// set dnsmasq listening interface and address
	fmt.Fprintln(&buf, "interface=eth0")
	fmt.Fprintln(&buf, "listen-address="+internalIP)
	fmt.Fprintln(&buf, "bind-interfaces")

	// ensure dnsmasq config directory exists
	if err := l.RunQuiet("sudo", "mkdir", "-p", "/etc/dnsmasq.d"); err != nil {
		return fmt.Errorf("failed to create dnsmasq config directory: %w", err)
	}

	// write config to dnsmasq directory
	if err := l.Write("/etc/dnsmasq.d/01-anvil.conf", buf.Bytes()); err != nil {
		return fmt.Errorf("failed to write dnsmasq config: %w", err)
	}

	// remove existing resolv.conf file
	if err := l.RunQuiet("sudo", "rm", "-f", "/etc/resolv.conf"); err != nil {
		return fmt.Errorf("failed to remove existing resolv.conf: %w", err)
	}

	// replace resolv.conf with a custom one
	resolvConf := fmt.Sprintf("# Generated by anvil\n\nnameserver %s\n", internalIP)
	if err := l.Write("/etc/resolv.conf", []byte(resolvConf)); err != nil {
		return fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	// restart dnsmasq service to apply changes
	if err := l.RunQuiet("sudo", "systemctl", "restart", "dnsmasq"); err != nil {
		return fmt.Errorf("failed to restart dnsmasq service: %w", err)
	}

	return nil
}

func (l *limaVM) setupSystemdResolved(dnsServers []string) error {
	// Build a systemd-resolved drop-in that uses the Lima gateway as primary
	// (so internal Lima hostnames still work) and public DNS as fallback.
	var primary, fallback []string
	for i, s := range dnsServers {
		if i == 0 {
			primary = append(primary, s)
		} else {
			fallback = append(fallback, s)
		}
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by anvil")
	fmt.Fprintln(&buf, "# Do not edit this file manually")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "[Resolve]")
	if len(primary) > 0 {
		fmt.Fprintf(&buf, "DNS=%s\n", strings.Join(primary, " "))
	}
	if len(fallback) > 0 {
		fmt.Fprintf(&buf, "FallbackDNS=%s\n", strings.Join(fallback, " "))
	}

	if err := l.RunQuiet("sudo", "mkdir", "-p", "/etc/systemd/resolved.conf.d"); err != nil {
		return fmt.Errorf("failed to create systemd-resolved config directory: %w", err)
	}

	if err := l.Write("/etc/systemd/resolved.conf.d/01-anvil.conf", buf.Bytes()); err != nil {
		return fmt.Errorf("failed to write systemd-resolved config: %w", err)
	}

	if err := l.RunQuiet("sudo", "systemctl", "restart", "systemd-resolved"); err != nil {
		return fmt.Errorf("failed to restart systemd-resolved: %w", err)
	}

	return nil
}

func (l *limaVM) writeResolvConf(dnsServers []string) error {
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by anvil")
	fmt.Fprintln(&buf)
	for _, dns := range dnsServers {
		fmt.Fprintf(&buf, "nameserver %s\n", dns)
	}

	if err := l.RunQuiet("sudo", "rm", "-f", "/etc/resolv.conf"); err != nil {
		return fmt.Errorf("failed to remove existing resolv.conf: %w", err)
	}

	if err := l.Write("/etc/resolv.conf", buf.Bytes()); err != nil {
		return fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	return nil
}
